In [ ]:
# !pip install numpy

In [4]:
print("start")

start


1. Create a vector with values ranging from 10 to 49.
2. Create a 3x3 matrix with values ranging from 0 to 8.
3. Create a 3x3 identity matrix.
4. Create a 3x3x3 array with random values.
5. Create a 10x10 array with random values and find the minimum and maximum values.
6. Create a random vector of size 30 and find the mean value.
7. Normalize a 5x5 random matrix.
8. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product).
9. Create two 3x3 matrices and compute their dot product.  
10. Given a 4x4 matrix, find its transpose.  
11. Create a 3x3 matrix and calculate its determinant.  
12. Create two matrices \( A \) (3x4) and \( B \) (4x3), and compute the matrix product \( A \cdot B \).  
13. Create a 3x3 random matrix and a 3-element column vector. Compute the matrix-vector product.  
14. Solve the linear system \( Ax = b \) where \( A \) is a 3x3 matrix, and \( b \) is a 3x1 column vector.  
15. Given a 5x5 matrix, find the row-wise and column-wise sums.

In [9]:
import numpy as np

a = np.arange(10, 50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [10]:
eight = np.arange(0, 9).reshape(3,3)
print(eight)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [12]:
identity = np.eye(3, 3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
randomm = np.random.random((10, 10))
max_val = randomm.max()
min_val = randomm.min()
print(randomm)
print(max_val)
print(min_val)


[[0.79629145 0.9280874  0.25532419 0.11926996 0.23407708 0.34001006
  0.88244238 0.69559283 0.1206148  0.70079313]
 [0.08243765 0.10392415 0.67328659 0.83978666 0.0424511  0.86768704
  0.43350206 0.89954727 0.77864443 0.57348085]
 [0.65239936 0.73956608 0.14765543 0.76818127 0.88714735 0.92018863
  0.5846837  0.58128437 0.31454831 0.68276707]
 [0.92653751 0.24740009 0.3277062  0.37720362 0.19377333 0.02323684
  0.91330569 0.18879029 0.92227023 0.70274558]
 [0.84877924 0.21666384 0.53852227 0.16233384 0.10581377 0.13337994
  0.58350862 0.6223104  0.67291726 0.42169686]
 [0.26691216 0.86837552 0.04035018 0.97432581 0.17718969 0.52009434
  0.06802769 0.33014088 0.68216767 0.34716828]
 [0.91693577 0.67551319 0.92766962 0.64126392 0.02158677 0.59939428
  0.34175286 0.01649279 0.72261354 0.57633955]
 [0.77981079 0.34511206 0.9770733  0.7236268  0.87584192 0.62362596
  0.61784982 0.26584461 0.2787243  0.96590285]
 [0.58279065 0.53930119 0.90118984 0.16260315 0.47368153 0.95414094
  0.34516407

In [20]:
randomm = np.random.random((3, 3))
print(randomm)

[[0.21507363 0.21598291 0.35271971]
 [0.46024941 0.35903505 0.79688962]
 [0.07186797 0.20549993 0.13304281]]


In [25]:
vect = np.random.random(30)
mean1 = vect.mean()
print(mean1)

0.5210537706335268


In [ ]:
norma = np.random.random((5, 5))
norm = (norma - norma.min())/(norma.max() - norma.min())
print(norm)

array([[0.34001792, 0.        , 0.66039484, 0.80188429, 0.14161335],
       [0.95778522, 0.93738327, 0.01580765, 0.55455149, 0.0046391 ],
       [0.66652478, 0.58984456, 0.51370887, 0.04089278, 0.09754342],
       [0.17068776, 0.18417512, 0.16832494, 0.12064384, 0.32391357],
       [1.        , 0.02221248, 0.34296035, 0.59833185, 0.19521013]])

In [36]:
mat1 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 7, 9],
    [5, 6, 6],
    [9, 6, 7]
])
mat2 = np.array([
    [2, 9],
    [4, 6],
    [8, 2]
])

mult = mat1 @ mat2
print(mult)

[[ 34  27]
 [ 76  78]
 [114 123]
 [ 82  93]
 [ 98 131]]


In [37]:
A = np.array([
    [1, 2, 1],
    [0, 1, 0],
    [2, 3, 4]
])

B = np.array([
    [2, 5, 1],
    [6, 7, 1],
    [1, 8, 1]
])
dot_pro = np.dot(A, B)
print(dot_pro)

[[15 27  4]
 [ 6  7  1]
 [26 63  9]]


In [39]:
real_mat = np.random.randint(1, 10, size = (4, 4))
print(f"real matrix:\n {real_mat}")

#tranponerlash
tr_mat = real_mat.T
print(f"transposed matrix:\n {tr_mat}")

real matrix:
 [[3 9 9 4]
 [7 1 7 1]
 [3 3 5 3]
 [7 8 8 6]]
transposed matrix:
 [[3 7 3 7]
 [9 1 3 8]
 [9 7 5 8]
 [4 1 3 6]]


In [40]:
mat = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
det = np.linalg.det(mat)
print(det)

0.0


In [41]:
A = np.random.randint(1, 10, size=(3, 4))
B = np.random.randint(1, 10, size=(4, 3))

cdot = A @ B
print(cdot)

[[189 120 161]
 [153  93 130]
 [119  79  90]]


In [43]:
A = np.random.randint(1, 10, size=(3, 3))
B = np.random.randint(1, 10, size=(3,))

product = A @ B

print(product)

[ 96 111  63]


In [47]:
A = np.array([
    [1, 2, 3],
    [4, 10, 6],
    [7, 8, 5]
])

b = np.array([10, 20, 30])

x = np.linalg.solve(A, b)
print(x)

[ 3.52941176 -1.17647059  2.94117647]


In [ ]:
A = np.random.randint(1, 10, size=(3, 3))

column_wise = A.sum(axis=0)
row_wise = A.sum(axis=1)
print(f"row wised sum:\n {row_wise}")
print(f"column wised sum:\n {column_wise}")

row wised sum:
 [17 12 15]
column wised sum:
 [15 13 16]
