In [3]:
import numpy as np

def f_to_c(f):
    return(f - 32) * 5/9

np_vectorized = np.vectorize(f_to_c)

temps = [100, 125, 75, 60]

temps_in_c =np_vectorized(temps)

print(temps_in_c)

[37.77777778 51.66666667 23.88888889 15.55555556]


In [4]:
def power(number, power):
    return number ** power
listpower = np.vectorize(power)

numbers = [3, 5, 9, 4]
powers = [4, 2, 3, 5]

powered_nums = listpower(numbers, powers)
print(powered_nums)

[  81   25  729 1024]


In [10]:
A = np.array([
    [4, 5, 6],
    [3, -1, 1],
    [2, 1, -2]
])

B = np.array([7, 4, 5])

solutions = np.linalg.solve(A, B)
print(solutions)

[ 1.7027027   0.62162162 -0.48648649]


In [11]:
A = np.array([
    [10, -2, 3],
    [-2, 8, -1],
    [3, -1, 6]
])

B = np.array([12, -5, 15])

solutions = np.linalg.solve(A, B)
print(solutions)

[ 0.48963731 -0.2253886   2.21761658]


In [13]:
import numpy as np
from PIL import Image
# Kichik 3x3 rangli rasm yaratamiz
# Har bir [R, G, B] bitta pikseldir
pixel_matrix = np.array([
    [[255, 0, 0],   [0, 255, 0],   [0, 0, 255]],  # 1-qator: Qizil, Yashil, Ko'k
    [[255, 255, 0], [255, 255, 255], [0, 0, 0]],   # 2-qator: Sariq, Oq, Qora
    [[128, 128, 128], [50, 50, 50], [200, 200, 200]] # 3-qator: Turli xil kulranglar
], dtype='uint8')

img = Image.fromarray(pixel_matrix)
img.save("first.png")
print("Asl Matritsa:\n", pixel_matrix)

Asl Matritsa:
 [[[255   0   0]
  [  0 255   0]
  [  0   0 255]]

 [[255 255   0]
  [255 255 255]
  [  0   0   0]]

 [[128 128 128]
  [ 50  50  50]
  [200 200 200]]]


In [2]:
import numpy as np

from PIL import Image

image = Image.open("./images/nature.jpg")
img_matrix = np.array(image)
print(img_matrix)

[[[137 155  97]
  [138 156  98]
  [138 156  98]
  ...
  [ 50  80  30]
  [ 37  67  13]
  [ 38  68   6]]

 [[137 155  97]
  [138 156  98]
  [138 156  98]
  ...
  [ 28  57   9]
  [ 44  74  22]
  [ 25  54   0]]

 [[137 155  97]
  [138 156  98]
  [138 156  98]
  ...
  [ 13  42   0]
  [  0  29   0]
  [ 22  50   2]]

 ...

 [[  7  17   6]
  [  9  19   8]
  [  6  16   5]
  ...
  [  8  16   5]
  [  8  16   3]
  [  9  17   2]]

 [[  6  16   7]
  [  9  19   8]
  [  9  19   8]
  ...
  [  8  16   5]
  [  8  16   3]
  [  8  16   1]]

 [[  4  14   5]
  [  3  13   4]
  [  8  18   7]
  ...
  [  9  17   6]
  [  9  17   4]
  [  4  12   0]]]


In [3]:
img_flip = np.flip(img_matrix, axis=0)
imgf = Image.fromarray(img_flip)
imgf.save("flipped.jpg")

In [18]:
img_flip1 = np.flip(img_matrix, axis=1)
imgf1 = Image.fromarray(img_flip1)
imgf1.save("flipped1.jpg")

In [24]:
import numpy as np

from PIL import Image

image = Image.open(r"C:\Users\bunyo\OneDrive\Desktop\python\lesson_14\images\birds.jpeg")
img_mat = np.array(image)
flp_bird = np.flip(img_mat, axis=(0, 1))
new_img = Image.fromarray(flp_bird)
new_img.save("flipped_bird.png")

In [27]:
noise = np.random.randint(0, 50, img_mat.shape, dtype='uint8')

noisy_bird_mat = img_mat.astype(np.uint16) + noise

noisy_bird_mat = np.clip(noisy_bird_mat, 0, 255).astype(np.uint8)
noisy_bird = Image.fromarray(noisy_bird_mat)
noisy_bird.save("noisy.png")

In [28]:
bright = img_mat.astype(np.uint16) + 50

bright = np.clip(bright, 0, 255).astype('uint8')
brighten_img = Image.fromarray(bright)
brighten_img.save("brighten_image.png")

In [30]:
mask_mat = img_mat.copy()

h, w, c = mask_mat.shape
center_h, center_w = h//2, w//2
mask_mat[center_h - 50 : center_h + 50, center_w - 50 : center_w + 50] = 0
masked_img = Image.fromarray(mask_mat)
masked_img.save("masked.jpeg")

In [1]:
print("hi")

hi
